
# Loads default set of integrations. Do not remove.
default_config:
    
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes 
  extra_module_url:
    - /local/card-mod.js

lovelace:
  mode: yaml
  resources: 
  - url: /local/xiaomi-vacuum-map-card.js
    type: module
  - url: /local/card-mod.js
    type: module  
  - url: /local/lovelace-horizon-card.js
    type: module  
  - url: /local/layout-card.js
    type: module  
  - url: /local/honeycomb-menu.js
    type: module  
  - url: /local/floorplan.js
    type: module     
  - url: /local/battery-state-card.js
    type: module     
  - url: /local/button-card.js
    type: module     
  - url: /local/swipe-navigation.js
    type: module     
  - url: /local/mushroom.js
    type: module     
  - url: /local/mini-graph-card-bundle.js
    type: module     
  - url: /local/simple-thermostat.js
    type: module     
  - url: /local/stack-in-card.js
    type: module     
  - url: /local/tabbed-card.js
    type: module     
  - url: /local/weather-radar-card.js
    type: module     
  dashboards:
    preview-dashboard:
      mode: yaml
      title: Aperçu
      icon: mdi:<icon>
      show_in_sidebar: true
      filename: './dashboards/preview.yaml'
    vacuums-dashboard:
      mode: yaml
      title: Neato
      icon: mdi:<icon>
      show_in_sidebar: true
      filename: './dashboards/vacuums.yaml'
    streaming-dashboard:
      mode: yaml
      title: Streaming
      icon: mdi:<icon>
      show_in_sidebar: true
      filename: './dashboards/streaming.yaml'
    status-dashboard:
      mode: yaml
      title: Status
      icon: mdi:<icon>
      show_in_sidebar: true
      filename: './dashboards/status.yaml'
    monitoring-dashboard:
      mode: yaml
      title: Monitoring
      icon: mdi:<icon>
      show_in_sidebar: true
      filename: './dashboards/monitoring.yaml'

# Waste collection schedule
# sensor are in sensors.yaml
waste_collection_schedule:
  sources:
    - name: recycleapp
      args:
        postcode: 7800
        street: Rue Carton
        house_number: 28
      customize:
        - type: PMD
          alias: PMC
        - type: Déchets résiduels
          alias: Résiduels
        - type: Déchets organiques
          alias: Organiques
        - type: Glass
          alias: Verre
        - type: Paper-cardboard
          alias: Papiers-Cartons

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include './customs/sensors.yaml'
switch: !include './customs/switchs.yaml'
template: !include './customs/templates.yaml'

# Define variables
var:
  light_above_couch:
    friendly_name: 'Lumière au dessus du canapé'
    initial_value: 0
    icon: mdi:bug
  y:
    friendly_name: 'Y'
    initial_value: 'Sleeping'
    entity_picture: '/local/sleep.png'