# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/community/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/lovelace-horizon-card/lovelace-horizon-card.js
      type: module
    - url: /local/community/honeycomb-menu/honeycomb-menu.js
      type: module
    - url: /local/community/ha-floorplan/floorplan.js
      type: module
    - url: /local/community/battery-state-card/battery-state-card.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/hass-swipe-navigation/swipe-navigation.js
      type: module
    - url: /local/community/lovelace-mushroom/mushroom.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/simple-thermostat/simple-thermostat.js
      type: module
    - url: /local/community/stack-in-card/stack-in-card.js
      type: module
    - url: /local/community/tabbed-card/tabbed-card.js
      type: module
    - url: /local/community/weather-radar-card/weather-radar-card.js
      type: module
    - url: /local/community/weather-card/weather-card.js
      type: module
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /local/community/decluttering-card/decluttering-card.js
      type: module
    - url: /local/community/lovelace-hourly-weather/hourly-weather.js
      type: module
    - url: /local/community/lovelace-windrose-card/windrose-card.js
      type: module  
    - url: /local/community/compass-card/compass-card.js
      type: module        
    - url: /local/community/apexcharts-card/apexcharts-card.js
      type: module
    - url: /local/community/weather-chart-card/weather-chart-card.js
      type: module  
    - url: /local/community/ha-card-weather-conditions/ha-card-weather-conditions.js
      type: module    
    - url: /local/community/ha-sankey-chart/ha-sankey-chart.js
      type: module           
    - url: /local/community/ha-sankey-chart/ha-sankey-chart.js
      type: module           
    - url: /local/community/PlexMeetsHomeAssistant/plex-meets-homeassistant.js
      type: module           
    - url: /local/community/upcoming-media-card/upcoming-media-card.js
      type: module                    
    - url: /local/community/mini-media-player/mini-media-player-bundle.js
      type: module 
    - url: /local/community/text-divider-row/text-divider-row.js
      type: module 
    - url: /local/community/decluttering-card/decluttering-card.js  
      type: module
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js  
      type: module
    - url: /local/community/bar-card/bar-card.js  
      type: module
    - url: /local/community/atomic-calendar-revive/atomic-calendar-revive.js  
      type: module      
  dashboards:
    preview-dashboard:
      mode: yaml
      title: Aperçu
      icon: mdi:eye-outline
      show_in_sidebar: true
      filename: "./dashboards/preview.yaml"
    floorplan-rdc-dashboard:
      mode: yaml
      title: Floorplan RDC
      icon: mdi:floor-plan
      show_in_sidebar: true
      filename: "./dashboards/floorplan_rdc.yaml"        
    floorplan-etage-dashboard:
      mode: yaml
      title: Floorplan Etage
      icon: mdi:floor-plan
      show_in_sidebar: true
      filename: "./dashboards/floorplan_etage.yaml"

# ICS (calendar) integration
ics_calendar:
  calendars:
    - name: "Sonarr"
      url: "http://10.191.107.50:8989/feed/v3/calendar/Sonarr.ics?apikey=0d5a05dc52d249208293c732c96e5c6e"
      include_all_day: true
      download_interval: 5
    - name: "Cha"
      url: "https://calendar.google.com/calendar/ical/chacha327%40gmail.com/public/basic.ics"
      include_all_day: true
      download_interval: 5
    - name: "Van"
      url: "https://p61-caldav.icloud.com/published/2/MTk0MTQ2ODEzOTE5NDE0NqGvZpoRCnDQONmXT0t3csmq_WeOzKe1EVXeSXxGXmDoQ_K5FcQrEeHwtTyLEuhBZ1ci-yIQYk--fO8PyDdLGII"
      include_all_day: true
      download_interval: 5

# Spotcast
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: BE #optional, added in 3.6.24
  #accounts:
  #  niklas:
  #    sp_dc: !secret niklas_sp_dc
  #    sp_key: !secret niklas_sp_key

# Waste collection schedule
# sensor are in sensors.yaml
waste_collection_schedule:
  sources:
    - name: recycleapp
      args:
        postcode: 7800
        street: Rue Carton
        house_number: 28
      customize:
        - type: PMD
          alias: PMC
        - type: Déchets résiduels
          alias: Résiduels
        - type: Déchets organiques
          alias: Organiques
        - type: Glass
          alias: Verre
        - type: Paper-cardboard
          alias: Papiers-Cartons

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include "./customs/sensors.yaml"
switch: !include "./customs/switchs.yaml"
template: !include "./customs/templates.yaml" 

