
# Loads default set of integrations. Do not remove.
default_config:
    
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes 
  extra_module_url:
    - /local/card-mod.js


# Waste collection schedule
# sensor are in sensors.yaml
waste_collection_schedule:
  sources:
    - name: recycleapp
      args:
        postcode: 7800
        street: Rue Carton
        house_number: 28
      customize:
        - type: PMD
          alias: PMC
        - type: Déchets résiduels
          alias: Résiduels
        - type: Déchets organiques
          alias: Organiques
        - type: Glass
          alias: Verre
        - type: Paper-cardboard
          alias: Papiers-Cartons

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include './customs/sensors.yaml'
switch: !include './customs/switchs.yaml'
template: !include './customs/templates.yaml'

# Define variables
var:
  light_above_couch:
    friendly_name: 'Lumière au dessus du canapé'
    initial_value: 0
    icon: mdi:bug
  y:
    friendly_name: 'Y'
    initial_value: 'Sleeping'
    entity_picture: '/local/sleep.png'